#page title
page_title                                : CVE Reference Tool | VDex

# App Info
ios_app_id                                : 1546459265

appstore_link                             : https://apps.apple.com/us/app/vdex/id1546459265
playstore_link                            : https://play.google.com/store/apps/details?id=com.g33kdev.vdex
# presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png
app_name                                  : VDex
app_price                                 : Free
app_description                           : Look up any CVE quickly and easily

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name: g33kdev                                
# your_link                                 : https://emilbaehr.com                     
# your_city                                 : Copenhagen                                
email_address: support@g33kdev.com
# facebook_username                         :                                           
# instagram_username                        : ebaehr
# twitter_username                          : ebaehr
# github_username                           : emilbaehr
# youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Up to Date CVEs
    description                           : CVEs are updated with data from NIST every hour.
    fontawesome_icon_name                 : sync
    
  - title                                 : Quick Lookup
    description                           : Quickly look up any CVE by CVE ID.
    fontawesome_icon_name                 : search

  - title                                 : Mobile Format
    description                           : View CVE summary, dates, CVSS and more.
    fontawesome_icon_name                 : mobile

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#5dabbd"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#5dabbd"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#5dabbd"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown